### ISSUE TITLE
[Feature]: Export the result as a JSON file

### ISSUE THREAD

**Issue by hongzzz** [web-infra-dev/rsdoctor#169]
### What problem does this feature solve?

Saving the JSON file of the results helps to discover the changes in package size for each version.

### What does the proposed API look like?

File like
```
{
  "size": "1000kb",
  "warnings": ["xxx"],
   ...
}
```

**Comment by easy1090** [comment]
I'll add this feature to TODO list.

**Comment by easy1090** [comment]
@hongzzz 
https://rsdoctor.dev/blog/release/release-note-0_3#custom-extension-rules 
https://rsdoctor.dev/guide/custom/upload-data

Because the Rsdoctor data is too large and contains residual information such as source code or bundled code, the bad data is completely thrown out, so an interface with custom rules has been developed, through which users can also filter the data and save it.
Can this meet your needs?

**Comment by hongzzz** [comment]
> @hongzzz https://rsdoctor.dev/blog/release/release-note-0_3#custom-extension-rules https://rsdoctor.dev/guide/custom/upload-data
> 
> Because the Rsdoctor data is too large and contains residual information such as source code or bundled code, the bad data is completely thrown out, so an interface with custom rules has been developed, through which users can also filter the data and save it. Can this meet your needs?

Yes.
