### ISSUE TITLE
[Bug]: Rsdoctor + Next.js

### ISSUE THREAD

**Issue by SLMNBJ** [web-infra-dev/rsdoctor#177]
### Version

```sh
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 92.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 121.0.6167.139
    Chrome Canary: 123.0.6268.0
    Edge: 121.0.2277.98
    Safari: 15.6
  npmPackages:
    @rsdoctor/webpack-plugin: ^0.1.1 => 0.1.1 
    next: 13.5.6
```

### Details

I'm trying to use Rsdoctor with Next.js. Currently I'm getting this error for different files
```
./src/pages/Maintenance/index.tsx
TypeError: Cannot read properties of undefined (reading 'traceChild')
    at /Users/bejaouis/projects/fe-n1-nextjs/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:163:54
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9)
```

![image](https://github.com/web-infra-dev/rsdoctor/assets/30017004/868d6bee-cbb0-49d8-b862-fdba405cafff)

this is how I add add Rsdoctor to webpack configuration  
![image](https://github.com/web-infra-dev/rsdoctor/assets/30017004/a9e38be2-87cc-486c-a2da-d75ced68cafa)

### Reproduce link

internal repo

### Reproduce Steps

not submitted

**Comment by easy1090** [comment]
Thanks, I'll try for this case.

**Comment by easy1090** [comment]
Before I make the next-swc-loader compatible, you can use other features except "loader"，
https://rsdoctor.dev/config/options/index#features.
such as:
```js
{
  features: ["plugins", "bundle"]
}
```

**Comment by SLMNBJ** [comment]
@easy1090 it works! thank you

**Comment by easy1090** [comment]
> TypeError: Cannot read properties of undefined (reading 'traceChild')

### Error Reasons:
- **Rsdoctor Loader logic:** Since Rsdoctor modifies the Loader Rules, Rsdoctor wraps the Module in a Proxy to support Loader logic with rule override.

- **Next.js specific logic:** In Next.js, the LoaderContext adds the currentTraceSpan property, which is obtained from the value retrieved using the Module as the key. 

However, since Rsdoctor wraps the Module in a Proxy (referred to as ProxyModule), retrieving the value using ProxyModule as the key will result in no value being obtained.

So, use module.traceChild will has error.

### Solution:
When You Encounter This Problem Using Next.js + Rsdoctor, You Can Use @rsdoctor/xxx >= 0.1.3.

### Notice:
However, in Next.js, when Rsdoctor is enabled and the build command is executed, the report server started by Rsdoctor will be disconnected. Therefore, if you need to reopen the report, you can use **@rsdoctor/cli** without performing the build operation.
https://rsdoctor.dev/guide/start/cli

### Next.js Notice Document:

https://rsdoctor.dev/guide/more/faq#nextjs
