### ISSUE TITLE
[Feature]: Output full html report to file with config name

### ISSUE THREAD

**Issue by zackarychapple** [web-infra-dev/rsdoctor#408]
### What problem does this feature solve?

Right now the only way to see the report is to have the page launch with rsdoctor cli or the plugin itself. 

### What does the proposed API look like?

have a configuration that supports `reportFilename` similar to bundle analyzer. This would allow for folders to be created with the config name and other options such as below.  This helps with uploading to CI/CD reporting servers for later viewing without needing to download the manifest and run the cli. 

```reportFilename: `${BUNDLE_ANALYZER}/report-${
            CONFIG.name
          }-${Date.now()}.html`,``` 
```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rsdoctor/issues/462
- [x] Output full html report to file with config name
```

**Comment by easy1090** [comment]
@zackarychapple 
This is planned, but because the Rsdoctor data is too large, the integration into an html may be slow and the page interaction may even crash. Therefore, the report after streamlining the data may be displayed. For example, the following key data:

- Error in the rules;

- Each Loader compiles time-consuming; (But, no display of the code before and after compilation for each file by each Loader);
 
- Each plugin takes time;

- Tree circle of products Bundles and Modules (no code details display).

Is the above plan in line with your idea?

**Comment by zackarychapple** [comment]
The biggest issue is that folks are wanting to add the Rsdoctor reports as something that is an artifact generated by the build pipeline for historical and reporting reasons.  Without an "offiline" way to output everything its challenging.

**Comment by easy1090** [comment]
> The biggest issue is that folks are wanting to add the Rsdoctor reports as something that is an artifact generated by the build pipeline for historical and reporting reasons. Without an "offiline" way to output everything its challenging.

I can understand this problem.

@zackarychapple Yes, I'm glad to talk more about this in DM's. lark or discord?

**Comment by easy1090** [comment]
@zackarychapple  This is coming. https://deploy-preview-488--rsdoctor.netlify.app/guide/start/cicd

**Comment by zackarychapple** [comment]
Very nice!  Thank you.
